const PATH = {
  home: '/',
  login: '/login',
  register: '/register',
  account: '/account',
  profile: '/account/profile',
  password: '/account/password',
  management: '/management',
  tours: '/management/my-tours',
  schedule: '/management/schedules',
  tourRequest: '/management/tour-requests',
  bookingsManagement: '/management/booked',
  salesReport: '/management/sales-reports',
  admin: '/admin',
  tourConfirmation: '/admin/tour-confirmation',
  tourList: '/admin/tour-list',
  guideConfirmation: '/admin/guide-confirmation',
  salesReportOfTour: '/admin/sales-report/tour',
  salesReportOfGuide: '/admin/sales-report/guide',
  reset: '/reset',
  changePasswordByToken: '/change-password-by-token',
  searchTour: 'tours/search',
  searchGuide: 'guides/search',
  tourDetail: '/tours/:id',
  guideProfile: '/guides/:id',
  cart: '/cart',
  checkout: '/cart/checkout',
  bookings: '/bookings',
  bookingSuccess: '/booking-success/:id',
  bookingFail: '/booking-fail',
  requestTour: '/request-add-tour',
  wishlist: '/wishlist',
  guideApplications: '/guide-applications',
  cryptoPayment: '/crypto-payment',
  invoices: '/invoices'
}

export default PATH
